

#ggplot2 --  Grammar of Graphics

# 7 Layers of information on a chart
# Data -> Aesthetics -> Goemetrics -> Statistics(create a new variable) -> Facets(same chart for different years) -> Coordinates(How you observe your data. e.g. x,y coordinates) -> Theme("Non-data linkT".itle, size of legend and everything that makes the chart pretty)

m.data <- read.csv(file.choose())
head(m.data)

#Removing unnecessary column
m.data$X <- NULL

str(m.data)
summary(m.data)

#converting into factor
# factor is like a categorical variable
#factor(m.data$Genre) --- gives output as vector
m.data$Genre <- factor(m.data$Genre) #passing the vector to the same column
m.data$Year.of.release <- factor(m.data$Year.of.release)
m.data$Film <- factor(m.data$Film) 

colnames(m.data)
colnames(m.data) <- c("Film", "Genre", "CriticRating", "AudienceRating", "BudgetMillion", "Year")


#---------------Aesthetic-----------------#

library(ggplot2) #loading the package using the library function

ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating ))

#adding Geometry
ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating )) + geom_point()

#adding color
ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating, color = Genre )) + 
  geom_point()

#add size
ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating, color = Genre, size = Genre )) + 
  geom_point()

#add size - in a better way
ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating, color = Genre, size = BudgetMillion )) + 
  geom_point()

#-------------Plotting with Layers---------------#

# +  ---> used to add layers to the object you are creating

p <- ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating, color = Genre, size = BudgetMillion ))
p

#points
p + geom_point()

#lines
p + geom_line()

#multiple layers
p + geom_point() + geom_line()
#changing the order of the layer
p + geom_line() + geom_point()


#-------------Overriding Aesthetics-------------#

q <- ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating,
                               color = Genre, size = BudgetMillion ))

#add geom layer
q + geom_point()

#overriding aes()
# ex 1 - overriding size
q + geom_point(aes(size = CriticRating))

# ex 2 - overriding color
q + geom_point(aes(color = BudgetMillion))
#q is not changing. only layer aesthetics is changing

# ex 3 - overriding x and y axis - because they are also aesthetics
q + geom_point(aes(x = BudgetMillion )) +
  xlab("BudgetMillion$") #even when we override the x axis, it still keeps the oldname(Criticrating). But we can fix it usinf xlab()
#>> 2nd chart

# ex 4
q + geom_line() + geom_point()
#reduce line size
q + geom_line(size = 1) + geom_point() #we are using setting here instead of mapping - changing size without aes() function


#-------------Mapping Vs Settings---------------#

r <- ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating))
r + geom_point()

#Add color
#1.Mapping (what we have done so far):
r + geom_point(aes(color = Genre))  # Genre is mapped to color

#2.Setting
r + geom_point(color = "DarkGreen")

#ERROR:
#r + geom_point(aes(color = "DarkGreen")) #R thinks you are mapping it to a variable that you created
#if you want to set a color don't use aesthetics. if you want to map a color to a variable then use aesthetics function (aes())


#1.Mapping
r + geom_point(aes(size = BudgetMillion))
#2.Setting
r + geom_point(size = 10)
#ERROR:
#r + geom_point(aes(size = 10)) #this size is not actually size 10


#------------Histogram and Density Charts-------------#

s <- ggplot(data = m.data, aes(x = BudgetMillion))
s + geom_histogram(binwidth = 10) #here count on y axis is generated by R

#add color
s + geom_histogram(binwidth = 10, aes(fill = Genre)) # here we used mapping for fill
#add a border
s + geom_histogram(binwidth = 10, aes(fill = Genre), color = "Black") #here we used setting for color
#>>Chart 3 

#sometimes you may need density charts:
s + geom_density(aes(fill = Genre)) #it gets overlapped so we use the position parameter 
s + geom_density(aes(fill = Genre), position = "stack") #for stacking one on another

#------------Starting Layer Tips-------------#

t = ggplot(data = m.data, aes(x = AudienceRating))
t + geom_histogram(binwidth = 10, fill = "White",
                   color = "Blue")

#another way to achieve same thing:
t <- ggplot(data = m.data)
t + geom_histogram(binwidth = 10,
                   aes(x = AudienceRating),
                   fill = "White",
                   color = "Blue")
#>>> Chart 4

#for CriticRating
t + geom_histogram(binwidth = 10,
                   aes(x = CriticRating),
                   fill = "White",
                   color = "Blue")
#>>> Chart 5

t <- ggplot() #Skeleton plot(empty plot). you can set the data inside the geom function


#----------Statistical Transformation---------#

?geom_smooth

u <- ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating, colour = Genre))
u + geom_point()
u + geom_point() + geom_smooth(fill = NA)

#boxplots for AudienceRating
u <- ggplot(data = m.data, aes(x = Genre, y = AudienceRating, colour = Genre))
u + geom_boxplot()
u + geom_boxplot(size = 1.2)
u + geom_boxplot(size = 1.2) +geom_point()
#tip / hack:
u + geom_boxplot(size = 1.2) +geom_jitter() # jitter - spreads the points. jitter is a good combination with box plot
#Always remember the order of layering

#Another way
u + geom_jitter() + geom_boxplot(size = 1.2, alpha = 0.5) 
#>> Chart 6

#boxplot for CriticRating
v <- ggplot(data = m.data, aes(x = Genre, y = CriticRating, colour = Genre))
v + geom_jitter() + geom_boxplot(size = 1.2, alpha = 0.5) 


#---------Using Facets-----------#

w <- ggplot(data = m.data, aes(x = BudgetMillion))
w + geom_histogram(binwidth = 10, aes(fill = Genre),
                   color = "Black")

#Facets - allows you to create lot of charts
w + geom_histogram(binwidth = 10, aes(fill = Genre),
                   color = "Black") +
facet_grid(Genre~., scales = "free") #scales = "free" - for providing different scales for each chart
?facet_grid #(Genre~.) can choose both side os tilde(~) symbol depending on what you want (row or column)


#scatterplots:
x <- ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating, colour = Genre))
x + geom_point(size = 3) + facet_grid(Genre~.)
x + geom_point(size = 3) + facet_grid(.~Year)
x + geom_point(size = 3) + facet_grid(Genre~Year) #rows - Genre : columns - Year

x + geom_point(size = 3)+geom_smooth() + facet_grid(Genre~Year) 
x + geom_point(aes(size = BudgetMillion))+geom_smooth() + facet_grid(Genre~Year) 
#>> Chart 1

#-------Coordinates---------#

m <- ggplot(data = m.data, aes(x = CriticRating, y = AudienceRating, size = BudgetMillion, color = Genre))
m + geom_point()
m + geom_point() + xlim(50,100) + ylim(50,100)#displaying only 50 to 100 in x-axis

#wont work well always
n <- ggplot(data = m.data, aes(x = BudgetMillion))
n + geom_histogram(binwidth = 10, aes(fill = Genre), color = "Black")

n + geom_histogram(binwidth = 10, aes(fill = Genre), color = "Black") +
  ylim(0,50) 

#instead - zoom:
n + geom_histogram(binwidth = 10, aes(fill = Genre), color = "Black") +
  coord_cartesian(ylim = c(0,50), xlim = c(0,200)) #pass limits you want to zoom as vectors

#improve chart 1
x + geom_point(aes(size = BudgetMillion)) +
  geom_smooth() + 
  facet_grid(Genre~Year) +
  coord_cartesian(ylim = c(0,100))

#---------Theme----------#

o <- ggplot(data = m.data, aes(x = BudgetMillion))
h <- o + geom_histogram(binwidth = 10, aes(fill = Genre), color = "black")

#add axes label

h + xlab("Money Axis") + ylab("Number of Movies") +
  theme(axis.title.x = element_text(color = "Darkgreen", size = 30),
        axis.title.y = element_text(color = "Red", size = 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20))
#?theme - see this to more options to make the chart look better

#Legend Formatting
h + xlab("Money Axis") + ylab("Number of Movies") +
  theme(axis.title.x = element_text(color = "Darkgreen", size = 30),
        axis.title.y = element_text(color = "Red", size = 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        
        legend.title = element_text(size = 30),
        legend.text = element_text(size = 20),
        legend.position = c(1,1), 
        legend.justification = c(1,1)) #putting top-right corner of legend on top-right corner of the chart

#Title
h + xlab("Money Axis") + 
  ylab("Number of Movies") +
  ggtitle("Movie Budget Distribution") +
  theme(axis.title.x = element_text(color = "Darkgreen", size = 30),
        axis.title.y = element_text(color = "Red", size = 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        
        legend.title = element_text(size = 30),
        legend.text = element_text(size = 20),
        legend.position = c(1,1), 
        legend.justification = c(1,1),#putting top-right corner of legend on top-right corner of the chart

        plot.title = element_text(color = "Darkblue", size = 30, family ="Courier")) 


#----------BoxPlot-------#

#more certainity with compact boxplot
#less certainity with wider boxplot
